name: songlib
description: An offline access to songs

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  card_swiper: ^2.0.4
  carousel_slider: ^4.1.1
  context_menus: ^1.0.2
  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  dio: ^4.0.6
  drift: ^1.7.1
  flutter_html: ^3.0.0-alpha.6
  flutter_keyboard_visibility: ^5.4.0
  flutter_secure_storage: ^5.0.2
  get_it: ^7.2.0
  fluttertoast: ^8.0.9
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.4
  flutter_localizations:
    sdk: flutter
  icapps_architecture: ^0.7.2
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  onboarding: ^3.1.0
  parse_server_sdk_flutter: ^3.1.3
  path: ^1.8.0
  path_provider: ^2.0.8
  percent_indicator: ^4.2.2
  provider: ^6.0.3
  pull_to_refresh: ^2.0.0
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.11
  share_plus: ^6.3.0
  sentry_flutter: ^6.18.0
  skeleton_loader: ^2.0.0+4
  timeago: ^3.3.0
  url_launcher: ^6.1.7
  wakelock: ^0.6.2
  workmanager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  drift_dev: ^1.7.1
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  icapps_license: ^2.0.0
  json_serializable: ^6.3.1
  locale_gen: ^4.1.2
  mockito: ^5.0.15
  model_generator: ^5.8.1
  retrofit_generator: ^4.0.3+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/locale/

locale_gen:
  default_language: 'en'
  languages: ['en', 'fr']
  locale_assets_path: 'assets/locale/'
  assets_path: 'assets/locale/'
  output_path: 'lib/utils/locale/'

icapps_license:
  nullsafety: true
  licenses:
    device_info: 'https://raw.githubusercontent.com/flutter/plugins/master/packages/device_info/device_info/LICENSE'
    flutter_cache_manager: 'https://raw.githubusercontent.com/Baseflow/flutter_cache_manager/develop/flutter_cache_manager/LICENSE'

targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
          nullable: true
